# Generated by Django 5.0.3 on 2024-04-05 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_author', models.CharField(max_length=200)),
                ('post_date', models.DateField(blank=True, default=None, null=True)),
                ('post_name', models.CharField(max_length=200)),
                ('post_status', models.CharField(max_length=200)),
                ('post_type', models.CharField(max_length=200)),
                ('comment_count', models.IntegerField()),
                ('like_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_login', models.CharField(max_length=200)),
                ('user_name', models.CharField(max_length=200)),
                ('display_name', models.CharField(max_length=200)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_password', models.CharField(max_length=200)),
                ('user_status', models.BinaryField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Post_Meta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_key', models.CharField(max_length=200)),
                ('meta_value', models.CharField(max_length=200)),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.posts')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_date', models.DateField(blank=True, default=None, null=True)),
                ('post_name', models.CharField(max_length=200)),
                ('comment_author', models.CharField(max_length=200)),
                ('comment_author_email', models.EmailField(max_length=254)),
                ('comment_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.posts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.users')),
            ],
        ),
    ]
