# Generated by Django 5.0.3 on 2024-03-28 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_author', models.CharField(max_length=200)),
                ('post_date', models.DateField(blank=True, default=None, null=True)),
                ('post_name', models.CharField(max_length=200)),
                ('post_status', models.CharField(max_length=200)),
                ('post_type', models.CharField(max_length=200)),
                ('comment_count', models.IntegerField()),
                ('like_count', models.IntegerField()),
            ],
        ),
    ]
