# Generated by Django 5.0.3 on 2024-04-05 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='user_status',
        ),
    ]
