# Generated by Django 5.0.3 on 2024-04-10 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_remove_users_user_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirQualityData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o2', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nox', models.DecimalField(decimal_places=2, max_digits=5)),
                ('so2', models.DecimalField(decimal_places=2, max_digits=5)),
                ('mg', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
