# Generated by Django 5.0.3 on 2024-04-10 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
