# Generated by Django 5.0.3 on 2024-09-07 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_delete_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AirQualityData',
        ),
        migrations.RemoveField(
            model_name='post_meta',
            name='post_id',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.DeleteModel(
            name='Post_Meta',
        ),
    ]
