# Generated by Django 5.0.3 on 2024-09-07 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_delete_airqualitydata_remove_post_meta_post_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Posts',
            new_name='Reviews',
        ),
    ]
